### ISSUE TITLE
skaffold image error

### ISSUE THREAD

**Issue by ysfAskri** [Activiti/activiti-cloud-connector-quickstart#9]
I have this error in the build 

```log
+ skaffold build -f skaffold.yaml
Complete in 2.313082ms
time="2019-05-22T09:08:33Z" level=fatal msg="creating runner: invalid skaffold config: required value not set: image"
```

this is my skaffold yaml file:

```yaml
apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/ysfaskri/activiti-rb-connector:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/ysfaskri/activiti-rb-connector:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: activiti-rb-connector
        chartPath: charts/activiti-rb-connector
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/ysfaskri/activiti-rb-connector'
          image.tag: '{{.DIGEST_HEX}}'

```
